version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx2g -Xms2g"
      ELASTIC_PASSWORD: changeme
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline/all:/usr/share/logstash/pipeline/all:ro
      - ./logstash/config/mysql-connector-java-5.1.44-bin.jar:/usr/share/logstash/config/mysql-connector-java-5.1.44-bin.jar

    ports:
      - "5000:5000"
      - "4000:4000"
      - "3000:3000"
      - "7000:7000"
      - "7500:7500"
      - "8000:8000"
      - "9000:9000"
      - "6000:6000"
      - "2000:2000"
    environment:
      LS_JAVA_OPTS: "-Xmx2g -Xmx2g"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:

  elk:
    driver: bridge
